[features]
seeds = false
[programs.localnet]
processing_instructions = "DgoL5J44aspizyUs9fcnpGEUJjWTLJRCfx8eYtUMYczf"

[registry]
url = ""

[provider]
 cluster = "https://solana-devnet.g.alchemy.com/v2/rj7MaDOTc5M1Zz0Z1R3u66d64y2PSXmo"
# cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
